2015-11-16 12:03:42,332 [Thread-2:1504] [django.request:170] [base:get_response] [WARNING]- Not Found: /
2015-11-16 14:27:43,411 [Thread-2:139888357742336] [django.request:170] [base:get_response] [WARNING]- Not Found: /
2015-11-16 14:36:03,155 [Thread-3:139888357742336] [django.request:170] [base:get_response] [WARNING]- Not Found: /
2015-11-16 14:36:03,954 [Thread-4:139888357742336] [django.request:170] [base:get_response] [WARNING]- Not Found: /
2015-11-16 14:43:07,918 [Thread-2:139679223150336] [django.request:170] [base:get_response] [WARNING]- Not Found: /
2015-11-16 14:43:08,696 [Thread-3:139679223150336] [django.request:170] [base:get_response] [WARNING]- Not Found: /
2015-11-16 14:43:09,105 [Thread-4:139679223150336] [django.request:170] [base:get_response] [WARNING]- Not Found: /
2015-11-16 14:43:09,310 [Thread-5:139679223150336] [django.request:170] [base:get_response] [WARNING]- Not Found: /
2015-11-16 14:43:09,507 [Thread-6:139679223150336] [django.request:170] [base:get_response] [WARNING]- Not Found: /
2015-11-16 14:43:09,686 [Thread-7:139679223150336] [django.request:170] [base:get_response] [WARNING]- Not Found: /
2015-11-16 14:43:09,862 [Thread-8:139679223150336] [django.request:170] [base:get_response] [WARNING]- Not Found: /
2015-11-16 14:43:10,044 [Thread-9:139679223150336] [django.request:170] [base:get_response] [WARNING]- Not Found: /
2015-11-16 14:43:10,252 [Thread-10:139679223150336] [django.request:170] [base:get_response] [WARNING]- Not Found: /
2015-11-16 14:43:10,434 [Thread-11:139679223150336] [django.request:170] [base:get_response] [WARNING]- Not Found: /
2015-11-16 14:43:10,612 [Thread-12:139679223150336] [django.request:170] [base:get_response] [WARNING]- Not Found: /
2015-11-16 14:43:10,821 [Thread-13:139679223150336] [django.request:170] [base:get_response] [WARNING]- Not Found: /
2015-11-16 14:43:11,052 [Thread-14:139679223150336] [django.request:170] [base:get_response] [WARNING]- Not Found: /
2015-11-16 14:44:34,488 [Thread-15:139679223150336] [django.request:170] [base:get_response] [WARNING]- Not Found: /
2015-11-16 14:44:35,011 [Thread-16:139679223150336] [django.request:170] [base:get_response] [WARNING]- Not Found: /
2015-11-16 14:44:35,236 [Thread-17:139679223150336] [django.request:170] [base:get_response] [WARNING]- Not Found: /
2015-11-16 14:44:35,425 [Thread-18:139679223150336] [django.request:170] [base:get_response] [WARNING]- Not Found: /
2015-11-16 14:44:35,608 [Thread-19:139679223150336] [django.request:170] [base:get_response] [WARNING]- Not Found: /
2015-11-16 14:44:35,805 [Thread-20:139679223150336] [django.request:170] [base:get_response] [WARNING]- Not Found: /
2015-11-16 14:44:35,998 [Thread-21:139679223150336] [django.request:170] [base:get_response] [WARNING]- Not Found: /
2015-11-21 14:40:23,312 [Thread-2:9704] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /scm/base/index/
Traceback (most recent call last):
  File "D:\Python34\lib\site-packages\django-1.8.6-py3.4.egg\django\core\urlresolvers.py", line 393, in urlconf_module
    return self._urlconf_module
AttributeError: 'RegexURLResolver' object has no attribute '_urlconf_module'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python34\lib\site-packages\django-1.8.6-py3.4.egg\django\core\handlers\base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "D:\Python34\lib\site-packages\django-1.8.6-py3.4.egg\django\core\urlresolvers.py", line 365, in resolve
    for pattern in self.url_patterns:
  File "D:\Python34\lib\site-packages\django-1.8.6-py3.4.egg\django\core\urlresolvers.py", line 401, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "D:\Python34\lib\site-packages\django-1.8.6-py3.4.egg\django\core\urlresolvers.py", line 395, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "D:\Python34\lib\importlib\__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "E:\scm\scm\urls.py", line 26, in <module>
    url(r'^admin/', include(admin.site.urls)),
  File "D:\Python34\lib\site-packages\django-1.8.6-py3.4.egg\django\contrib\admin\sites.py", line 291, in urls
    return self.get_urls(), 'admin', self.name
  File "D:\Python34\lib\site-packages\django-1.8.6-py3.4.egg\django\contrib\admin\sites.py", line 250, in get_urls
    self.check_dependencies()
  File "D:\Python34\lib\site-packages\django-1.8.6-py3.4.egg\django\contrib\admin\sites.py", line 173, in check_dependencies
    "Put 'django.contrib.admin' in your INSTALLED_APPS "
django.core.exceptions.ImproperlyConfigured: Put 'django.contrib.admin' in your INSTALLED_APPS setting in order to use the admin application.
